apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: kakarot0503/my-app:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
          
  ---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: my-app
      k8s-app: my-app
    name: my-app
  spec:
    ports:
    - name: http
      port: 80
      targetPort: 8085
    type: LoadBalancer
    selector:
      app: my-app
