---
- hosts: server
  become: True
  tasks:
    - name: "Install PIP"
      apt: name=python3-pip state=present

    - name: "Install lxml"
      pip: name=lxml

    - name: "pulling  war file from nexus and deploying"
      maven_artifact:
        group_id: in.javahome
        artifact_id: myweb
        extension: war
        version: "{{ver}}"
        repository_url: "http://172.31.40.187:8081/repository/ansible_rep/"
        username: admin
        password: Supersaiyan@1
        dest: "/opt/tomcat/webapps/myweb-{{ver}}.war"
        mode: '0644'
